### PR TITLE
Support JCA files

### PR DESCRIPTION
**Pull request by lumag**
Add support for outputting JCA files via ant-javacard.

### CODE REVIEW

**Comment by martinpaljak** [comment]
Please also add documentation to the README where the usage instructions are.

**Comment by martinpaljak** [comment]
As the idea would be to add "human readable usability", maybe hiding the JCA generation under "debug" flag ?

**Comment by lumag** [comment]
Updated the README file.
I'm not so sure about the "debug" flag. In the end the JCA is the same type of build artifact as export files are.

**Comment by lumag** [comment]
@martinpaljak any update or additional action required wrt. these patches?

**Comment by martinpaljak** [comment]
Looks good, thanks!

**Pull request merged**
